/home/kuic/anaconda3/envs/OliVe/lib/python3.8/site-packages/torch/distributed/launch.py:208: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use-env is set by default in torchrun.
If your script expects `--local-rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  main()
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).
[rank0]: Traceback (most recent call last):
[rank0]:   File "run_clm.py", line 689, in <module>
[rank0]:     main()
[rank0]:   File "run_clm.py", line 291, in main
[rank0]:     model_args, data_args, training_args, quantizer_args = parser.parse_args_into_dataclasses()
[rank0]:   File "/home/kuic/anaconda3/envs/OliVe/lib/python3.8/site-packages/transformers/hf_argparser.py", line 341, in parse_args_into_dataclasses
[rank0]:     raise ValueError(f"Some specified arguments are not used by the HfArgumentParser: {remaining_args}")
[rank0]: ValueError: Some specified arguments are not used by the HfArgumentParser: ['--local-rank=0']
E0824 11:18:49.376625 139748054995584 torch/distributed/elastic/multiprocessing/api.py:833] failed (exitcode: 1) local_rank: 0 (pid: 360388) of binary: /home/kuic/anaconda3/envs/OliVe/bin/python
Traceback (most recent call last):
  File "/home/kuic/anaconda3/envs/OliVe/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/kuic/anaconda3/envs/OliVe/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/kuic/anaconda3/envs/OliVe/lib/python3.8/site-packages/torch/distributed/launch.py", line 208, in <module>
    main()
  File "/home/kuic/anaconda3/envs/OliVe/lib/python3.8/site-packages/typing_extensions.py", line 2853, in wrapper
    return arg(*args, **kwargs)
  File "/home/kuic/anaconda3/envs/OliVe/lib/python3.8/site-packages/torch/distributed/launch.py", line 204, in main
    launch(args)
  File "/home/kuic/anaconda3/envs/OliVe/lib/python3.8/site-packages/torch/distributed/launch.py", line 189, in launch
    run(args)
  File "/home/kuic/anaconda3/envs/OliVe/lib/python3.8/site-packages/torch/distributed/run.py", line 892, in run
    elastic_launch(
  File "/home/kuic/anaconda3/envs/OliVe/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 133, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/kuic/anaconda3/envs/OliVe/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
run_clm.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-08-24_11:18:49
  host      : Retal
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 360388)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
